branches:
  - main
  - name: develop
    prerelease: beta
  - name: next
    prerelease: rc
  - name: alpha
    prerelease: alpha
  - name: fork
    prerelease: fork
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/changelog'
    - changelogFile: docs/CHANGELOG.md
  - '@semantic-release/github'
  - - '@semantic-release/git'
    - assets:
        - docs/CHANGELOG.md
