# TODO: refactor this workflow to trigger after ci job has finished
name: Build and Semantic Release
on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'next'
      - 'alpha'
      - 'fork'
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  build_release:
    env:
      GITHUB_TOKEN: ${{ secrets.TYPEDORM_BOT_PAT }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # fetch all pervious history to be able to properly generate changelog
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Semantic Release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v3
      - name: Trigger publish
        if: steps.semantic_release.outputs.new_release_published == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{secrets.TYPEDORM_BOT_PAT}}
          workflow: NPM Publish
